### ISSUE TITLE
Render canvas on provided container

### ISSUE THREAD

**Issue by pedroalmeida415** [btco/qx82#4]
It'd be nice if we could give an ID or an element itself to the initializer to tell it where to render the canvas, instead of just creating and appending a new canvas to the body

**Comment by btco** [comment]
Good idea!

**Comment by btco** [comment]
Thinking about this, but it's non-trivial because the canvas needs to have a pretty specific configuration in terms of width, height, etc to match the config...

**Comment by photonstorm** [comment]
I think the request is just asking to pass an id where the canvas will be appended (it's parent element) as opposed to adding it directly in the body.

I agree there's no point adding a feature to pass in a canvas element to actually use, but a parent makes sense.

**Comment by btco** [comment]
Ahh yes, that makes sense, but still the code is currently hard-coded to
have the canvas the same size as window.innerWidth x window.innerHeight
(cropped to aspect). If I refactor that a bit, I think I can then accept a
parent element.

I will look into it. Thanks!

Le sam. 21 oct. 2023 à 10:58, Richard Davey ***@***.***> a
écrit :

**Comment by btco** [comment]
Just a note that I'm currently working on this and expect to have a solution soon-ish.

**Comment by btco** [comment]
There is now also a way to specify:
* What element the canvas should be added to (CONFIG.CANVAS_SETTINGS.CONTAINER)
* Whether or not QX82 should auto-position and/or auto-size the canvas (CONFIG.CANVAS_SETTINGS.AUTO_POSITION and AUTO_SIZE)
* What ID and CSS classes to assign to the canvas (CONFIG.CANVAS_SETTINGS.CANVAS_ID and CANVAS_CLASSES).
